spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cruddb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:crud_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:crud_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
